// ============================================================================
// Datos del curso "Pensamiento analítico y lógico" (UVP, primer semestre)
// Metadatos, trayectorias y banco de ejercicios con retroalimentación automática.
// El texto de referencia completo (teoría + niveles + bancos por trayectoria)
// vive en referencia.js, generado a partir del manual del curso.
// ============================================================================

const TRAYECTORIAS = [
  { id: 'T1', nombre: 'Diseño y Moda' },
  { id: 'T2', nombre: 'Gastronomía' },
  { id: 'T3', nombre: 'Derecho' },
  { id: 'T4', nombre: 'Administración y Negocios' },
  { id: 'T5', nombre: 'Negocios Internacionales' },
  { id: 'T6', nombre: 'Ingeniería y Sistemas' },
  { id: 'T7', nombre: 'Salud y Psicología' },
];

const MODULOS = [
  { id: 1, nombre: 'Lógica proposicional', sesiones: [1, 2, 3, 4] },
  { id: 2, nombre: 'Teoría de conjuntos', sesiones: [5, 6, 7, 8] },
  { id: 3, nombre: 'Relaciones', sesiones: [9, 10, 11, 12] },
  { id: 4, nombre: 'Funciones', sesiones: [13, 14, 15, 16] },
];

const SESIONES = {
  1:  { modulo: 1, titulo: 'El lenguaje proposicional: formalizar', semana: 'Semana 1' },
  2:  { modulo: 1, titulo: 'Tablas de verdad: valor, clasificación y validez', semana: 'Semanas 2–3' },
  3:  { modulo: 1, titulo: 'Deducción natural I: las reglas de la prueba', semana: 'Semana 4' },
  4:  { modulo: 1, titulo: 'Deducción natural II: supuestos, absurdo y casos', semana: 'Semanas 5–6' },
  5:  { modulo: 2, titulo: 'Conjunto, pertenencia e inclusión', semana: 'Semana 7' },
  6:  { modulo: 2, titulo: 'Operaciones y diagramas de Venn', semana: 'Semana 8' },
  7:  { modulo: 2, titulo: 'Álgebra de conjuntos y conjunto potencia', semana: 'Semana 9' },
  8:  { modulo: 2, titulo: 'Producto cartesiano', semana: 'Semana 10' },
  9:  { modulo: 3, titulo: 'Relaciones binarias: dominio, rango e inversa', semana: 'Semana 11' },
  10: { modulo: 3, titulo: 'Propiedades de las relaciones', semana: 'Semana 12' },
  11: { modulo: 3, titulo: 'Equivalencia, clases y particiones', semana: 'Semanas 12–13' },
  12: { modulo: 3, titulo: 'Relaciones de orden y diagramas de Hasse', semana: 'Semana 13' },
  13: { modulo: 4, titulo: 'Concepto de función: dominio, codominio, imagen', semana: 'Semana 14' },
  14: { modulo: 4, titulo: 'Inyectiva, sobreyectiva, biyectiva', semana: 'Semana 15' },
  15: { modulo: 4, titulo: 'Composición de funciones', semana: 'Semana 15' },
  16: { modulo: 4, titulo: 'Función inversa y síntesis del curso', semana: 'Semana 16' },
};

// ----------------------------------------------------------------------------
// Banco de ejercicios con retroalimentación automática.
// Tipos: 'vf' | 'opcion' | 'numero' | 'formula' | 'conjunto'
// ----------------------------------------------------------------------------

const EJERCICIOS = {

// ============================= MÓDULO 1 ====================================

1: [
  { id:'1.2', tipo:'vf', nivel:1, enunciado:'«¡Cierra la puerta!» es una proposición.',
    respuesta:false, explicacion:'Es un mandato: no afirma un hecho que pueda ser verdadero o falso. Queda fuera de la lógica proposicional junto con preguntas, exclamaciones y normas.' },
  { id:'1.5', tipo:'vf', nivel:1, enunciado:'«2 + 2 = 5» es una proposición.',
    respuesta:true, explicacion:'Toda oración declarativa completa es proposición, sea verdadera o falsa. «2+2=5» es perfectamente respetable como proposición: simplemente es falsa.' },
  { id:'1.17', tipo:'opcion', nivel:1, enunciado:'¿Por qué «Prohibido fumar» no es una proposición?',
    opciones:['Es una pregunta','Es una norma: no afirma un hecho','Es un fragmento sin verbo conjugado','Es una cadena agramatical'],
    correcta:1, explicacion:'Una norma no describe cómo es el mundo, prescribe cómo debería ser. En cambio «en este edificio no se puede fumar» sí es proposición, porque describe una regla vigente como hecho.' },
  { id:'1.24', tipo:'opcion', nivel:1, enunciado:'¿Cuál es la conectiva principal de «No es cierto que si estudio, apruebo»?',
    opciones:['∧ (conjunción)','∨ (disyunción)','→ (implicación)','¬ (negación)'],
    correcta:3, explicacion:'La negación gobierna toda la fórmula: ¬(E→A). La implicación queda encerrada dentro del alcance de la negación.' },
  { id:'1.22', tipo:'opcion', nivel:1, enunciado:'¿Cuál es la conectiva principal de «Vino Ana pero no Luis»?',
    opciones:['∧ (conjunción)','∨ (disyunción)','→ (implicación)','↔ (coimplicación)'],
    correcta:0, explicacion:'«Pero» es psicológicamente un contraste, pero lógicamente es conjunción: afirma las dos cosas a la vez (A ∧ ¬L).' },
  { id:'1.31', tipo:'vf', nivel:1, enunciado:'¬¬p es una fórmula bien formada.',
    respuesta:true, explicacion:'Si p es fbf, ¬p también lo es; y si ¬p es fbf, ¬¬p también. La negación se puede aplicar cuantas veces se quiera.' },
  { id:'1.34', tipo:'vf', nivel:1, enunciado:'p ∧ ∨ q es una fórmula bien formada.',
    respuesta:false, explicacion:'Una conectiva binaria (∧, ∨, →, ↔) necesita una fórmula completa a cada lado. Aquí ∧ queda seguida directamente de ∨, sin fórmula entre ellas: no es fbf.' },
  { id:'1.41', tipo:'formula', nivel:2, enunciado:'Formaliza: «Si llueve, me mojo» (L: llueve; M: me mojo).',
    respuestas:['L→M'], explicacion:'«Si p, entonces q» es exactamente p→q: L→M.', placeholder:'Usa la paleta de símbolos ↓' },
  { id:'1.52', tipo:'formula', nivel:2, enunciado:'Formaliza: «No es cierto que llueva y haga sol» (L: llueve; S: hay sol).',
    respuestas:['¬(L∧S)'], explicacion:'«No es cierto que p y q» niega toda la conjunción: ¬(L∧S). Ojo: no es lo mismo que ¬L∧¬S.' },
  { id:'1.51', tipo:'formula', nivel:2, enunciado:'Formaliza: «Me mojo si y solo si llueve y no traigo paraguas» (L: llueve; M: me mojo; P: traigo paraguas).',
    respuestas:['M↔(L∧¬P)'], explicacion:'«A si y solo si B» es A↔B. Aquí A = M y B = «llueve y no traigo paraguas» = L∧¬P.' },
  { id:'1.25', tipo:'formula', nivel:2, enunciado:'Formaliza: «Ni fumo ni bebo» (F: fumo; B: bebo).',
    respuestas:['¬F∧¬B'], explicacion:'«Ni p ni q» es ¬p∧¬q: se escriben dos negaciones, una por cada átomo. ¬(F∧B) sería un error: diría algo mucho más débil.' },
  { id:'1.69a', tipo:'opcion', nivel:3, enunciado:'«p a menos que q» se formaliza como:',
    opciones:['p→q','¬q→p','q→p','¬p→¬q'],
    correcta:1, explicacion:'«A menos que» invierte el condicional respecto de lo que parece a simple vista: p a menos que q ≡ ¬q→p (equivalente a p∨q).' },
  { id:'1.71', tipo:'opcion', nivel:3, enunciado:'«Apruebas solo si entregas el proyecto» (A: apruebas; E: entregas el proyecto) se formaliza como:',
    opciones:['A→E','E→A','A↔E','¬A→E'],
    correcta:0, explicacion:'«p solo si q» es p→q: «solo si» introduce el consecuente, no el antecedente. Es el error más común de la sesión.' },
  { id:'1.69', tipo:'formula', nivel:3, enunciado:'Formaliza: «No salgo a menos que deje de llover» (S: salgo; L: llueve).',
    respuestas:['L→¬S'], explicacion:'«No salgo» (¬S) a menos que «deje de llover» (¬L) sigue el patrón p a menos que q ≡ ¬q→p, con p=¬S y q=¬L: ¬(¬L)→¬S, es decir L→¬S. Léelo en español: «si sigue lloviendo, no salgo».' },
  { id:'1.76', tipo:'formula', nivel:3, enunciado:'Formaliza: «Ana y Luis no vinieron los dos» (A: vino Ana; L: vino Luis).',
    respuestas:['¬(A∧L)'], explicacion:'«No ambos» niega la conjunción completa: ¬(A∧L). Es distinto de «ninguno vino» (¬A∧¬L), que es mucho más fuerte.' },
],

2: [
  { id:'2.1', tipo:'vf', nivel:1, enunciado:'Con p = V y q = F: el valor de p ∧ q es verdadero.',
    respuesta:false, explicacion:'La conjunción es verdadera solo cuando ambas partes lo son. Con q falso, p∧q = F.' },
  { id:'2.4', tipo:'vf', nivel:1, enunciado:'Con p = V y q = F: el valor de p → q es verdadero.',
    respuesta:false, explicacion:'La implicación falla exactamente cuando el antecedente es verdadero y el consecuente falso. Ese es justo este caso: p→q = F.' },
  { id:'2.6', tipo:'vf', nivel:1, enunciado:'Con p = V y q = F: el valor de q → p es verdadero.',
    respuesta:true, explicacion:'F→V es verdadero: la implicación solo falla con antecedente verdadero y consecuente falso. Aquí el antecedente (q) ya es falso, así que la implicación se sostiene automáticamente. Es el caso que casi todo el grupo falla a primera vista.' },
  { id:'2.8', tipo:'vf', nivel:1, enunciado:'Con p = V y q = F: el valor de ¬p ∨ q es verdadero.',
    respuesta:false, explicacion:'¬p = F y q = F, luego ¬p∨q = F∨F = F.' },
  { id:'2.classif1', tipo:'opcion', nivel:2, enunciado:'Clasifica (p → q) ∧ ¬q:',
    opciones:['Tautología','Contradicción','Contingencia'],
    correcta:2, explicacion:'La tabla completa da V solo en el renglón p=F,q=F: es verdadera en algunos casos y falsa en otros. Contingencia.' },
  { id:'2.classif2', tipo:'opcion', nivel:1, enunciado:'Clasifica p ∨ ¬p:',
    opciones:['Tautología','Contradicción','Contingencia'],
    correcta:0, explicacion:'Es verdadera en todos los renglones posibles, por su pura forma. Tautología.' },
  { id:'2.classif3', tipo:'opcion', nivel:1, enunciado:'Clasifica p ∧ ¬p:',
    opciones:['Tautología','Contradicción','Contingencia'],
    correcta:1, explicacion:'Es falsa en todos los renglones posibles. Contradicción.' },
  { id:'2.cuidado', tipo:'vf', nivel:2, enunciado:'p → q es lógicamente equivalente a ¬p → ¬q.',
    respuesta:false, explicacion:'¬p→¬q es la inversa, no la contrapositiva, y NO es equivalente. «Si llueve me mojo» no implica «si no llueve no me mojo» (podría caer a una alberca). La contrapositiva correcta es ¬q→¬p.' },
  { id:'2.contrapos', tipo:'formula', nivel:2, enunciado:'Escribe la contrapositiva de p → q.',
    respuestas:['¬q→¬p'], explicacion:'La contrapositiva invierte y niega ambos lados: ¬q→¬p. Sí es equivalente a la original.' },
  { id:'2.valid1', tipo:'opcion', nivel:2, enunciado:'¿Es válido el argumento p→q, q ⊢ p?',
    opciones:['Sí, es válido','No: falacia de afirmación del consecuente'],
    correcta:1, explicacion:'Con p=F, q=V: las premisas pueden ser verdaderas y la conclusión falsa. Es la falacia de afirmación del consecuente.' },
  { id:'2.valid2', tipo:'opcion', nivel:2, enunciado:'¿Es válido el argumento p→q, ¬q ⊢ ¬p?',
    opciones:['Sí: es modus tollens','No es válido'],
    correcta:0, explicacion:'No existe ningún renglón con p→q y ¬q verdaderas y ¬p falsa. Es modus tollens, válido.' },
  { id:'2.rows', tipo:'numero', nivel:1, enunciado:'¿Cuántos renglones tiene la tabla de verdad de una fórmula con 3 variables distintas?',
    respuesta:8, explicacion:'2³ = 8. Cada variable duplica el número de casos.' },
  { id:'2.contraej', tipo:'vf', nivel:2, enunciado:'Para mostrar que un argumento es inválido, basta con exhibir un solo renglón (contraejemplo).',
    respuesta:true, explicacion:'Un renglón donde las premisas son verdaderas y la conclusión falsa basta para probar invalidez. En cambio, para probar validez hay que revisar toda la tabla.' },
],

3: [
  { id:'3.1', tipo:'opcion', nivel:1, enunciado:'De las premisas «1. p» y «2. p → q», ¿qué se puede obtener de inmediato?',
    opciones:['q, por E→ 1,2','p∧q, por I∧ 1,2','nada: falta información'],
    correcta:0, explicacion:'Con el antecedente (p) y la implicación (p→q) ya disponibles, se aplica eliminación de la implicación (modus ponens): q.' },
  { id:'3.3', tipo:'opcion', nivel:1, enunciado:'De la premisa «1. p ∧ q», ¿qué se puede obtener directamente?',
    opciones:['p, por E∧ 1','p∨r, por I∧ 1','q→p, por E→ 1'],
    correcta:0, explicacion:'La eliminación de la conjunción (E∧) saca cualquiera de las dos partes por separado, cada una con su propia línea y justificación.' },
  { id:'3.mt', tipo:'opcion', nivel:2, enunciado:'¿Qué regla permite pasar de «p → q» y «¬q» a «¬p»?',
    opciones:['MT (modus tollens)','SD (silogismo disyuntivo)','E→ (eliminación de la implicación)'],
    correcta:0, explicacion:'Modus tollens: de A→B y ¬B se obtiene ¬A. Es una regla derivada, permitida como atajo.' },
  { id:'3.sd', tipo:'opcion', nivel:2, enunciado:'¿Qué regla permite pasar de «p ∨ q» y «¬p» a «q»?',
    opciones:['MT (modus tollens)','SD (silogismo disyuntivo)','I∨ (introducción de la disyunción)'],
    correcta:1, explicacion:'Silogismo disyuntivo: de A∨B y ¬A se obtiene B.' },
  { id:'3.iv1', tipo:'vf', nivel:1, enunciado:'De «p» se puede concluir «p ∨ q» para cualquier fórmula q, aunque q no tenga nada que ver.',
    respuesta:true, explicacion:'La introducción de la disyunción (I∨) solo pide que al menos una de las dos partes sea verdadera. «Llueve, luego llueve o soy el rey de China» es correcto.' },
  { id:'3.iv2', tipo:'vf', nivel:1, enunciado:'De «p ∨ q» se puede concluir «p» directamente.',
    respuesta:false, explicacion:'No existe esa regla. La disyunción no se elimina así: para sacar algo concreto de p∨q hace falta prueba por casos (E∨), que se ve en la sesión 4.' },
  { id:'3.pasos', tipo:'numero', nivel:2, enunciado:'En la derivación de p→q, q→r, p ⊢ r: ¿cuántos pasos adicionales hacen falta después de escribir las tres premisas?',
    respuesta:2, explicacion:'Paso 4: q por E→ (1,3). Paso 5: r por E→ (2,4). Dos pasos.' },
  { id:'3.blank', tipo:'formula', nivel:1, enunciado:'Dadas «1. p → q, prem.» y «2. p, prem.», ¿qué fórmula se escribe en la línea 3 (justificada con E→ 1,2)?',
    respuestas:['q'], explicacion:'E→ (modus ponens) aplicada a p→q y p produce q.' },
  { id:'3.cero', tipo:'vf', nivel:1, enunciado:'Un renglón de una derivación sin justificación vale cero, no es un simple descuento.',
    respuesta:true, explicacion:'Sin justificación, el paso es una afirmación inventada. La regla de oro del formato: si no puedes escribir la justificación, el paso no existe.' },
],

4: [
  { id:'4.i1', tipo:'opcion', nivel:1, enunciado:'Para probar una meta A → B con la regla I→, ¿qué se hace?',
    opciones:['Se supone A y se intenta derivar B dentro de una subprueba','Se supone B y se deriva A','Se busca A∧B directamente'],
    correcta:0, explicacion:'Prueba condicional: se abre una subprueba suponiendo A; si dentro se logra B, se cierra escribiendo A→B afuera.' },
  { id:'4.i2', tipo:'opcion', nivel:1, enunciado:'Para probar ¬A por reducción al absurdo, ¿qué se hace?',
    opciones:['Se supone A y se busca una contradicción dentro de la subprueba','Se supone ¬A directamente como premisa','Se deriva A y luego se niega'],
    correcta:0, explicacion:'I¬: se supone A; si dentro se derivan una fórmula y su negación (⊥), se cierra la subprueba y se escribe ¬A afuera.' },
  { id:'4.alcance', tipo:'vf', nivel:1, enunciado:'Una vez cerrada una subprueba, se pueden citar sus líneas internas fuera de ella.',
    respuesta:false, explicacion:'La regla del alcance: las líneas internas de una subprueba cerrada están muertas. Solo sobrevive la conclusión que autoriza la regla de cierre. Violar esto es un error grave: equivale a afirmar como probado algo que solo se supuso.' },
  { id:'4.eor', tipo:'opcion', nivel:2, enunciado:'La regla E∨ (prueba por casos) requiere, para una disyunción A∨B, que se pruebe:',
    opciones:['Que de A se sigue C y que de B se sigue la misma C, en dos subpruebas separadas','Solo que A implique C','Que A y B sean verdaderas a la vez'],
    correcta:0, explicacion:'Dos subpruebas, una por caso, llegando ambas a la misma conclusión C. Es el esquema del dilema constructivo.' },
  { id:'4.teorema', tipo:'vf', nivel:2, enunciado:'⊢ p → (q → p) es un teorema: se puede probar sin ninguna premisa.',
    respuesta:true, explicacion:'Se supone p, luego se supone q, se reitera p, se cierra con I→ dos veces. Una derivación sin premisas prueba una tautología.' },
  { id:'4.peirce', tipo:'vf', nivel:3, enunciado:'La ley de Peirce, ((p → q) → p) → p, es una tautología.',
    respuesta:true, explicacion:'Sí lo es, aunque el método abreviado de buscar un contraejemplo directo no lo encuentra fácilmente: hace falta construir la derivación con subpruebas para verlo con claridad.' },
  { id:'4.dn', tipo:'opcion', nivel:1, enunciado:'De «¬¬p» se puede obtener directamente «p» aplicando la ley de:',
    opciones:['Doble negación (DN)','Modus tollens (MT)','Silogismo disyuntivo (SD)'],
    correcta:0, explicacion:'¬¬p ≡ p es la ley de doble negación, una de las equivalencias notables.' },
],

// ============================= MÓDULO 2 ====================================

5: [
  { id:'5.1', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación 1 ∈ A es verdadera.',
    respuesta:true, explicacion:'1 está listado explícitamente como elemento de A.' },
  { id:'5.2', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación {1} ∈ A es verdadera.',
    respuesta:false, explicacion:'A no contiene al conjunto {1} como elemento; contiene al número 1, que no es lo mismo que la caja {1}.' },
  { id:'5.3', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación {1} ⊆ A es verdadera.',
    respuesta:true, explicacion:'Como 1 ∈ A, el conjunto {1} —cuyo único elemento es 1— es subconjunto de A.' },
  { id:'5.5', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación {4,5} ∈ A es verdadera.',
    respuesta:true, explicacion:'{4,5} está listado literalmente como uno de los elementos de A.' },
  { id:'5.6', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación {4,5} ⊆ A es verdadera.',
    respuesta:false, explicacion:'Para que {4,5} ⊆ A haría falta que 4 ∈ A y 5 ∈ A por separado, y ninguno de los dos lo es (solo está la caja {4,5} completa).' },
  { id:'5.8', tipo:'vf', nivel:1, enunciado:'Con A = {1, 2, 3, {4,5}, ∅}: la afirmación ∅ ∈ A es verdadera.',
    respuesta:true, explicacion:'∅ está listado como elemento de A: es una caja vacía guardada dentro de A.' },
  { id:'5.9', tipo:'vf', nivel:1, enunciado:'∅ ⊆ A para cualquier conjunto A.',
    respuesta:true, explicacion:'No hay ningún elemento de ∅ que pudiera fallar la condición de pertenecer a A: es un condicional de antecedente siempre falso, y esos son siempre verdaderos.' },
  { id:'5.decide', tipo:'opcion', nivel:1, enunciado:'¿Cuál de estas dos definiciones decide todos los casos, sin ambigüedad?',
    opciones:['«Los alumnos aplicados»','«Los alumnos con promedio mayor o igual a 8.5 al cierre del semestre»'],
    correcta:1, explicacion:'Un conjunto por comprensión solo está bien definido si su condición decide sin empates para cada objeto del universo. «Aplicado» depende de quién opine; el umbral numérico no.' },
  { id:'5.vacios', tipo:'vf', nivel:1, enunciado:'∅ = {∅}',
    respuesta:false, explicacion:'∅ tiene cero elementos; {∅} tiene un elemento (una caja vacía adentro). No son el mismo conjunto.' },
  { id:'5.card', tipo:'numero', nivel:2, enunciado:'¿Cuánto vale |{a, a, b}|?',
    respuesta:2, explicacion:'La repetición no cuenta: {a,a,b} = {a,b}, que tiene 2 elementos.' },
  { id:'5.subconj', tipo:'numero', nivel:2, enunciado:'¿Cuántos subconjuntos tiene un conjunto de 4 elementos?',
    respuesta:16, explicacion:'2⁴ = 16. Cada elemento se decide independientemente: entra o no entra.' },
  { id:'5.extension', tipo:'conjunto', nivel:2, enunciado:'Escribe por extensión, sobre N = {0,1,2,...}: {x : x < 6}',
    respuestas:['{0,1,2,3,4,5}'], explicacion:'Los naturales menores que 6, empezando en 0: {0,1,2,3,4,5}.' },
],

6: [
  { id:'6.union', tipo:'conjunto', nivel:1, enunciado:'Con U={1..10}, A={1,2,3,4}, B={3,4,5,6}: calcula A ∪ B.',
    respuestas:['{1,2,3,4,5,6}'], explicacion:'La unión junta todo lo que está en A, en B, o en ambos, sin repetir.' },
  { id:'6.inter', tipo:'conjunto', nivel:1, enunciado:'Con A={1,2,3,4}, B={3,4,5,6}: calcula A ∩ B.',
    respuestas:['{3,4}'], explicacion:'La intersección es lo que está en los dos a la vez.' },
  { id:'6.dif', tipo:'conjunto', nivel:1, enunciado:'Con A={1,2,3,4}, B={3,4,5,6}: calcula A \\ B.',
    respuestas:['{1,2}'], explicacion:'A\\B es lo que está en A y no en B: quitamos 3 y 4 (que sí están en B), quedan 1 y 2.' },
  { id:'6.compl', tipo:'conjunto', nivel:1, enunciado:'Con U={1,...,10}, A={1,2,3,4}: calcula Aᶜ.',
    respuestas:['{5,6,7,8,9,10}'], explicacion:'El complemento es todo lo del universo que no está en A.' },
  { id:'6.card', tipo:'numero', nivel:1, enunciado:'Con A={1,2,3,4}, B={3,4,5,6}: ¿cuánto vale |A ∪ B|?',
    respuesta:6, explicacion:'A∪B = {1,2,3,4,5,6}, que tiene 6 elementos.' },
  { id:'6.disjuntos', tipo:'vf', nivel:1, enunciado:'Con A={1,2,3,4} y C={5,6,7}: A y C son disjuntos.',
    respuesta:true, explicacion:'No comparten ningún elemento, así que A ∩ C = ∅: son disjuntos.' },
  { id:'6.incexc1', tipo:'numero', nivel:2, enunciado:'|A|=12, |B|=9, |A∩B|=4. Calcula |A ∪ B|.',
    respuesta:17, explicacion:'|A∪B| = |A|+|B|-|A∩B| = 12+9-4 = 17.' },
  { id:'6.incexc2', tipo:'numero', nivel:2, enunciado:'En un grupo de 30: 22 usan Netflix, 18 usan Spotify, 3 no usan ninguno. ¿Cuántos usan los dos servicios?',
    respuesta:13, explicacion:'27 usan al menos uno (30-3). Por inclusión-exclusión: 27 = 22+18-x, luego x = 40-27 = 13.' },
  { id:'6.incexc3', tipo:'numero', nivel:2, enunciado:'Con los mismos datos del ejercicio anterior (22 Netflix, 18 Spotify, 13 ambos): ¿cuántos usan solo Netflix?',
    respuesta:9, explicacion:'Los que usan Netflix (22) menos los que usan ambos (13): 22-13 = 9.' },
  { id:'6.region', tipo:'opcion', nivel:1, enunciado:'¿Cómo se escribe «lo que está en A y en B pero no en C»?',
    opciones:['(A∩B)\\C','(A∪B)\\C','A∩(B∪C)','A\\(B∩C)'],
    correcta:0, explicacion:'Primero A∩B (los dos a la vez), y de ahí se quita todo lo que caiga en C.' },
],

7: [
  { id:'7.ley1', tipo:'opcion', nivel:1, enunciado:'¿Qué ley justifica A ∩ (B ∪ A) = A?',
    opciones:['Conmutativa','Absorción','De Morgan','Idempotencia'],
    correcta:1, explicacion:'La ley de absorción: A ∩ (A ∪ B) = A. El orden de B y A dentro de la unión no afecta.' },
  { id:'7.ley2', tipo:'opcion', nivel:1, enunciado:'¿Qué ley justifica (A ∪ B)ᶜ = Aᶜ ∩ Bᶜ?',
    opciones:['De Morgan','Distributiva','Absorción','Identidad'],
    correcta:0, explicacion:'Es la ley de De Morgan para conjuntos, gemela de ¬(p∨q) ≡ ¬p∧¬q en lógica.' },
  { id:'7.potencia1', tipo:'numero', nivel:1, enunciado:'Si |A| = 6, ¿cuánto vale |P(A)|?',
    respuesta:64, explicacion:'|P(A)| = 2ⁿ = 2⁶ = 64.' },
  { id:'7.potencia2', tipo:'numero', nivel:1, enunciado:'Si |P(A)| = 32, ¿cuánto vale |A|?',
    respuesta:5, explicacion:'2⁵ = 32, así que |A| = 5.' },
  { id:'7.potencia3', tipo:'vf', nivel:1, enunciado:'∅ ∈ P(A) para cualquier conjunto A.',
    respuesta:true, explicacion:'∅ es subconjunto de cualquier A, así que siempre es elemento de P(A).' },
  { id:'7.potencia4', tipo:'vf', nivel:1, enunciado:'A ∈ P(A) para cualquier conjunto A.',
    respuesta:true, explicacion:'A es subconjunto de sí mismo, así que A siempre pertenece a P(A).' },
  { id:'7.simp1', tipo:'conjunto', nivel:2, enunciado:'Simplifica A ∪ (A ∩ B) a su forma más corta.',
    respuestas:['A'], explicacion:'Es la ley de absorción: A ∪ (A ∩ B) = A.' },
  { id:'7.simp2', tipo:'conjunto', nivel:2, enunciado:'Simplifica (A ∩ B) ∪ (A ∩ Bᶜ) a su forma más corta.',
    respuestas:['A'], explicacion:'Por distributiva: A ∩ (B ∪ Bᶜ) = A ∩ U = A.' },
  { id:'7.dif', tipo:'opcion', nivel:1, enunciado:'A \\ B se puede escribir de forma equivalente como:',
    opciones:['A ∩ Bᶜ','A ∪ Bᶜ','Aᶜ ∩ B','Aᶜ ∪ Bᶜ'],
    correcta:0, explicacion:'«Lo que está en A y no en B» es exactamente A ∩ Bᶜ.' },
  { id:'7.pp', tipo:'numero', nivel:2, enunciado:'¿Cuántos elementos tiene P(P({a})) ?',
    respuesta:4, explicacion:'P({a}) = {∅,{a}} tiene 2 elementos, luego P(P({a})) tiene 2² = 4 elementos.' },
],

8: [
  { id:'8.card1', tipo:'numero', nivel:1, enunciado:'Con A={1,2}, B={a,b,c}: ¿cuánto vale |A × B|?',
    respuesta:6, explicacion:'|A×B| = |A|·|B| = 2·3 = 6.' },
  { id:'8.orden1', tipo:'vf', nivel:1, enunciado:'(1, 2) = (2, 1)',
    respuesta:false, explicacion:'Un par ordenado distingue el orden: (1,2) ≠ (2,1). Solo son iguales si coinciden en ambas coordenadas.' },
  { id:'8.orden2', tipo:'vf', nivel:1, enunciado:'{1, 2} = {2, 1}',
    respuesta:true, explicacion:'Un conjunto no distingue el orden: {1,2} y {2,1} son el mismo conjunto.' },
  { id:'8.vacio', tipo:'numero', nivel:2, enunciado:'Si |A| = 5 y |B| = 0, ¿cuánto vale |A × B|?',
    respuesta:0, explicacion:'Si B no tiene elementos, no hay con qué formar la segunda coordenada: A×B = ∅.' },
  { id:'8.menu', tipo:'numero', nivel:2, enunciado:'Un menú tiene 4 platos, 3 bebidas y 2 postres. ¿Cuántas comidas completas distintas se pueden armar?',
    respuesta:24, explicacion:'4 · 3 · 2 = 24 combinaciones distintas de plato-bebida-postre.' },
  { id:'8.hallaB', tipo:'numero', nivel:2, enunciado:'Si |A × B| = 24 y |A| = 6, ¿cuánto vale |B|?',
    respuesta:4, explicacion:'|B| = |A×B| / |A| = 24/6 = 4.' },
  { id:'8.vf1', tipo:'vf', nivel:1, enunciado:'A × ∅ = ∅ para cualquier conjunto A.',
    respuesta:true, explicacion:'Sin elementos en el segundo conjunto, no se puede formar ningún par: el producto es vacío.' },
  { id:'8.vf2', tipo:'vf', nivel:2, enunciado:'Si |A × B| = 12, entonces necesariamente |A| = 3 y |B| = 4.',
    respuesta:false, explicacion:'12 también se factoriza como 1×12, 2×6, 4×3, 6×2 o 12×1. El producto cartesiano solo fija el producto de las cardinalidades, no cuáles son.' },
  { id:'8.relacion', tipo:'opcion', nivel:1, enunciado:'Una relación de A en B es, por definición:',
    opciones:['Un subconjunto del producto cartesiano A × B','Cualquier función de A en B','El conjunto A ∪ B'],
    correcta:0, explicacion:'El producto cartesiano es todo lo que podría estar vinculado; una relación es un subconjunto de eso: lo que efectivamente está vinculado.' },
],

// ============================= MÓDULO 3 ====================================

9: [
  { id:'9.dom', tipo:'conjunto', nivel:1, enunciado:'Con A={1,2,3,4}, B={a,b,c}, R={(1,a),(1,b),(2,c),(4,a)}: da el dominio de R.',
    respuestas:['{1,2,4}'], explicacion:'El dominio son los elementos de A que sí tienen algo relacionado: 1, 2 y 4 (el 3 queda fuera).' },
  { id:'9.ran', tipo:'conjunto', nivel:1, enunciado:'Con la misma R={(1,a),(1,b),(2,c),(4,a)}: da el rango (imagen) de R.',
    respuestas:['{a,b,c}'], explicacion:'El rango son los elementos de B que son alcanzados por alguna flecha: a (por 1 y 4), b (por 1) y c (por 2). Los tres están cubiertos.' },
  { id:'9.huerfano', tipo:'numero', nivel:1, enunciado:'Con A={1,2,3,4} y dom R={1,2,4}: ¿qué elemento de A es huérfano (no está en el dominio)?',
    respuesta:3, explicacion:'3 es el único elemento de A que no aparece como primera coordenada de ningún par de R.' },
  { id:'9.card', tipo:'numero', nivel:1, enunciado:'¿Cuántos pares tiene R = {(1,a),(1,b),(2,c),(4,a)}?',
    respuesta:4, explicacion:'Son cuatro pares ordenados distintos.' },
  { id:'9.axb', tipo:'numero', nivel:1, enunciado:'Con A={1,2,3,4} y B={a,b,c}: ¿cuánto vale |A × B|?',
    respuesta:12, explicacion:'|A×B| = 4·3 = 12.' },
  { id:'9.cuantas', tipo:'numero', nivel:2, enunciado:'¿Cuántas relaciones distintas existen en un conjunto de 3 elementos (relaciones de A en A con |A|=3)?',
    respuesta:512, explicacion:'|A×A| = 9, y una relación es cualquier subconjunto de esas 9 casillas: 2⁹ = 512.' },
  { id:'9.inversa_ex', tipo:'vf', nivel:1, enunciado:'La relación inversa de cualquier relación siempre existe: cualquier relación se puede dar vuelta sin condiciones.',
    respuesta:true, explicacion:'Invertir es solo cambiar el orden de cada par. A diferencia de las funciones (sesión 16), toda relación tiene inversa.' },
  { id:'9.inversa_calc', tipo:'conjunto', nivel:2, enunciado:'Sobre {1,2,3}, sea R = {(1,2), (2,3)}. Escribe R⁻¹ como conjunto de pares (formato: (a,b),(c,d) ).',
    respuestas:['(2,1),(3,2)','(3,2),(2,1)'], explicacion:'Se invierte cada par: (1,2) da (2,1), y (2,3) da (3,2).' },
  { id:'9.domInv', tipo:'opcion', nivel:2, enunciado:'dom(R⁻¹) es siempre igual a:',
    opciones:['ran(R)','dom(R)','A × B'],
    correcta:0, explicacion:'Al invertir los pares, lo que antes era rango ahora es dominio: dom(R⁻¹) = ran(R).' },
],

10: [
  { id:'10.refl', tipo:'vf', nivel:1, enunciado:'La relación «≤» sobre los naturales es reflexiva.',
    respuesta:true, explicacion:'a ≤ a se cumple siempre, para todo a.' },
  { id:'10.sim', tipo:'vf', nivel:1, enunciado:'La relación «≤» sobre los naturales es simétrica.',
    respuesta:false, explicacion:'Contraejemplo: 1 ≤ 2 pero no 2 ≤ 1.' },
  { id:'10.antisim', tipo:'vf', nivel:1, enunciado:'La relación «≤» sobre los naturales es antisimétrica.',
    respuesta:true, explicacion:'Si a ≤ b y b ≤ a, entonces necesariamente a = b.' },
  { id:'10.trans', tipo:'vf', nivel:1, enunciado:'La relación «≤» sobre los naturales es transitiva.',
    respuesta:true, explicacion:'Si a ≤ b y b ≤ c, entonces a ≤ c.' },
  { id:'10.vacia', tipo:'vf', nivel:2, enunciado:'La relación vacía (∅) en cualquier conjunto A es simétrica.',
    respuesta:true, explicacion:'Se cumple vacuamente: como nunca hay un par (a,b) en la relación, el condicional «si (a,b)∈R entonces (b,a)∈R» nunca tiene antecedente verdadero, así que siempre es verdadero.' },
  { id:'10.confusion', tipo:'vf', nivel:2, enunciado:'«No ser simétrica» es lo mismo que «ser antisimétrica».',
    respuesta:false, explicacion:'Son cosas distintas: una relación puede no ser simétrica y tampoco ser antisimétrica a la vez (ej. {(1,2),(2,1),(1,3)}: le falta (3,1) para ser simétrica, pero tiene la pareja doble 1↔2 que rompe la antisimetría).' },
  { id:'10.hermano', tipo:'opcion', nivel:2, enunciado:'¿Es transitiva la relación «es hermano de» sobre un conjunto de personas?',
    opciones:['Sí, siempre','No: falla cuando a = c, porque nadie es hermano de sí mismo'],
    correcta:1, explicacion:'Si a es hermano de b y b de c, se esperaría que a sea hermano de c, salvo cuando a=c, caso en que la conclusión («a es hermano de sí mismo») es falsa. Por un pelo, no es transitiva.' },
  { id:'10.matriz', tipo:'opcion', nivel:1, enunciado:'En la matriz de una relación, ser reflexiva se ve como:',
    opciones:['Puros 1 en la diagonal principal','Puros 0 en la diagonal principal','La matriz es igual a su transpuesta'],
    correcta:0, explicacion:'Cada (a,a) está en la relación exactamente cuando la diagonal tiene un 1 en esa posición.' },
  { id:'10.doble', tipo:'vf', nivel:2, enunciado:'Una relación puede ser simétrica y antisimétrica a la vez (por ejemplo, la relación identidad IA).',
    respuesta:true, explicacion:'La diagonal IA = {(a,a): a∈A} cumple ambas propiedades sin contradicción: no hay pares con a≠b que violen ninguna de las dos.' },
],

11: [
  { id:'11.igualdad', tipo:'vf', nivel:1, enunciado:'La relación «a = b» es una relación de equivalencia.',
    respuesta:true, explicacion:'Es reflexiva, simétrica y transitiva: el caso más simple de equivalencia.' },
  { id:'11.leq', tipo:'vf', nivel:1, enunciado:'La relación «a ≤ b» es una relación de equivalencia.',
    respuesta:false, explicacion:'No es simétrica (1≤2 no implica 2≤1). Le falta esa propiedad para ser equivalencia.' },
  { id:'11.hermano', tipo:'vf', nivel:1, enunciado:'La relación «a es hermano de b» es una relación de equivalencia.',
    respuesta:false, explicacion:'No es reflexiva (nadie es hermano de sí mismo) ni transitiva en el caso a=c. Falla dos de las tres condiciones.' },
  { id:'11.part1', tipo:'opcion', nivel:2, enunciado:'Sobre A={1,...,6}: ¿es partición la familia {{1,2},{3,4},{5,6}}?',
    opciones:['Sí, es partición','No: se traslapan dos bloques','No: dejan elementos fuera'],
    correcta:0, explicacion:'Los tres bloques son no vacíos, disjuntos dos a dos, y su unión cubre {1,...,6}. Cumple las tres condiciones.' },
  { id:'11.part2', tipo:'opcion', nivel:2, enunciado:'Sobre A={1,...,6}: ¿es partición la familia {{1,2,3},{3,4,5,6}}?',
    opciones:['Sí, es partición','No: los bloques se traslapan (3 está en los dos)','No: falta un bloque'],
    correcta:1, explicacion:'El elemento 3 aparece en ambos bloques: no son disjuntos. No es partición.' },
  { id:'11.part3', tipo:'opcion', nivel:2, enunciado:'Sobre A={1,...,6}: ¿es partición la familia {{1,2},{3,4}}?',
    opciones:['Sí, es partición','No: no cubre todo A (faltan 5 y 6)','No: hay un bloque vacío'],
    correcta:1, explicacion:'5 y 6 no están en ningún bloque: la familia no cubre A. No es partición.' },
  { id:'11.part4', tipo:'opcion', nivel:2, enunciado:'Sobre A={1,...,6}: ¿es partición la familia {{1,2}, ∅, {3,4,5,6}}?',
    opciones:['Sí, es partición','No: contiene un bloque vacío'],
    correcta:1, explicacion:'Una partición exige que ningún bloque sea vacío. El ∅ ahí presente la invalida, aunque el resto cubra y sea disjunto.' },
  { id:'11.clases', tipo:'numero', nivel:2, enunciado:'Si |A|=12 y una relación de equivalencia produce clases de exactamente 3 elementos cada una, ¿cuántas clases hay?',
    respuesta:4, explicacion:'12 / 3 = 4 clases, ya que las clases de una partición son disjuntas y cubren todo A.' },
  { id:'11.mod3', tipo:'numero', nivel:1, enunciado:'¿Cuántas clases de equivalencia produce la relación «mismo residuo módulo 3» sobre los naturales?',
    respuesta:3, explicacion:'Los residuos posibles al dividir entre 3 son 0, 1 y 2: exactamente tres clases, [0], [1] y [2].' },
],

12: [
  { id:'12.leq', tipo:'opcion', nivel:1, enunciado:'La relación «≤» sobre los naturales es un orden:',
    opciones:['Total: cualquier par de números se puede comparar','Parcial, con elementos incomparables'],
    correcta:0, explicacion:'Dos naturales cualesquiera siempre se pueden comparar con ≤: es orden total.' },
  { id:'12.subseteq', tipo:'opcion', nivel:1, enunciado:'La relación «⊆» sobre P(X), con |X| ≥ 2, es un orden:',
    opciones:['Total','Parcial: por ejemplo, {a} y {b} son incomparables'],
    correcta:1, explicacion:'Ni {a}⊆{b} ni {b}⊆{a}: son incomparables. ⊆ es orden parcial, no total.' },
  { id:'12.divide', tipo:'opcion', nivel:1, enunciado:'La relación «a divide a b» sobre los naturales es un orden:',
    opciones:['Total','Parcial: por ejemplo, 2 y 3 son incomparables'],
    correcta:1, explicacion:'2 no divide a 3 ni 3 divide a 2: son incomparables. Es orden parcial.' },
  { id:'12.incomp', tipo:'vf', nivel:1, enunciado:'Un orden parcial puede tener elementos incomparables entre sí.',
    respuesta:true, explicacion:'Justo esa es la diferencia con un orden total, que exige que cualquier par sea comparable.' },
  { id:'12.maxunico', tipo:'vf', nivel:2, enunciado:'En un orden parcial, si existe un máximo, este es único.',
    respuesta:true, explicacion:'Se demuestra con antisimetría: si hubiera dos máximos m1 y m2, cada uno estaría por encima del otro, y la antisimetría forzaría m1=m2.' },
  { id:'12.maximal', tipo:'opcion', nivel:2, enunciado:'La diferencia entre «maximal» y «máximo» es:',
    opciones:['Maximal: nadie por encima de él (puede haber varios). Máximo: está por encima de todos (único si existe)','Son exactamente lo mismo','Maximal es único; máximo puede haber varios'],
    correcta:0, explicacion:'Si el Hasse termina en dos puntas distintas, hay dos maximales y no hay máximo: dos autoridades últimas sin nadie que las desempate.' },
  { id:'12.ciclo', tipo:'vf', nivel:2, enunciado:'Un ciclo en una jerarquía de prerrequisitos (A antes de B, B antes de C, C antes de A) demuestra que el sistema es inejecutable.',
    respuesta:true, explicacion:'Un orden parcial no puede tener ciclos (lo impiden la antisimetría y la transitividad). Si el grafo real tiene uno, el sistema no se puede cursar tal como está escrito.' },
  { id:'12.hasse1', tipo:'numero', nivel:2, enunciado:'En el Hasse de «divide a» sobre {1,2,3,4,6,12}: ¿cuántos elementos maximales hay?',
    respuesta:1, explicacion:'Solo 12 no tiene nada por encima (nada en el conjunto es múltiplo propio de 12). Un solo maximal.' },
  { id:'12.hasse2', tipo:'numero', nivel:2, enunciado:'En el mismo Hasse de «divide a» sobre {1,2,3,4,6,12}: ¿cuántos elementos minimales hay?',
    respuesta:1, explicacion:'Solo 1 no tiene nada por debajo (1 no es múltiplo propio de ningún otro elemento del conjunto). Un solo minimal.' },
],

// ============================= MÓDULO 4 ====================================

13: [
  { id:'13.f1', tipo:'opcion', nivel:1, enunciado:'Con A={1,2,3}, B={a,b,c}: {(1,a),(2,a),(3,a)} ¿es función de A en B?',
    opciones:['Sí: cada entrada tiene exactamente una salida','No: falla la totalidad','No: falla la unicidad'],
    correcta:0, explicacion:'Cada uno de 1, 2 y 3 tiene exactamente una imagen (todas dan «a»). Es función legítima, aunque desperdicie casi todo el codominio.' },
  { id:'13.f2', tipo:'opcion', nivel:1, enunciado:'Con A={1,2,3}, B={a,b,c}: {(1,a),(1,b),(2,c),(3,c)} ¿es función?',
    opciones:['Sí','No: el 1 tiene dos imágenes (falla la unicidad)','No: falla la totalidad'],
    correcta:1, explicacion:'El elemento 1 aparece con dos salidas distintas, a y b. Eso rompe la unicidad.' },
  { id:'13.f3', tipo:'opcion', nivel:1, enunciado:'Con A={1,2,3}, B={a,b,c}: {(1,a),(2,b)} ¿es función de A en B?',
    opciones:['Sí','No: falla la unicidad','No: el 3 no tiene imagen (falla la totalidad)'],
    correcta:2, explicacion:'El elemento 3 de A se queda sin ninguna salida asignada: falla la totalidad.' },
  { id:'13.curp', tipo:'vf', nivel:1, enunciado:'«A cada persona, su CURP» es una función.',
    respuesta:true, explicacion:'Toda persona tiene exactamente una CURP: se cumplen totalidad y unicidad.' },
  { id:'13.raiz', tipo:'vf', nivel:1, enunciado:'«A cada número real, su raíz cuadrada» (con codominio los reales) es una función.',
    respuesta:false, explicacion:'Los números negativos no tienen raíz real (falla totalidad) y, sin declarar una convención, un número positivo tendría dos raíces, +√x y -√x (falla unicidad).' },
  { id:'13.uno_sobre_x', tipo:'opcion', nivel:2, enunciado:'f(x) = 1/x sobre los reales: ¿qué condición falla?',
    opciones:['La totalidad: el 0 no tiene imagen','La unicidad: hay dos imágenes posibles','Ninguna: sí es función tal cual'],
    correcta:0, explicacion:'No se puede dividir entre 0, así que el 0 se queda sin imagen. Se arregla restringiendo el dominio a R\\{0}.' },
  { id:'13.imagen_sub', tipo:'vf', nivel:1, enunciado:'La imagen de una función siempre es subconjunto del codominio declarado.',
    respuesta:true, explicacion:'im f ⊆ B por definición: la imagen son las salidas que de hecho se usan, y son parte de las salidas posibles.' },
  { id:'13.inalcanz', tipo:'vf', nivel:2, enunciado:'Puede existir una función válida donde algún elemento del codominio nunca sea alcanzado por ninguna entrada.',
    respuesta:true, explicacion:'Eso no rompe la función (la totalidad exige que el dominio se cubra, no el codominio). Es simplemente una salida inalcanzable: un dato de auditoría, no una falla de la función.' },
],

14: [
  { id:'14.2x', tipo:'opcion', nivel:1, enunciado:'f(x) = 2x, de Z en Z, es:',
    opciones:['Inyectiva, no sobreyectiva','Sobreyectiva, no inyectiva','Biyectiva','Ninguna de las dos cosas'],
    correcta:0, explicacion:'Es inyectiva (2x=2y implica x=y), pero no sobreyectiva: el 3 no es imagen de ningún entero.' },
  { id:'14.2xpares', tipo:'opcion', nivel:1, enunciado:'La misma f(x) = 2x, ahora de Z en los números pares, es:',
    opciones:['Inyectiva, no sobreyectiva','Biyectiva','Ni inyectiva ni sobreyectiva'],
    correcta:1, explicacion:'Sigue siendo inyectiva, y ahora también sobreyectiva porque todo par es 2 veces algún entero. Biyectiva: no cambió la fórmula, cambió el codominio.' },
  { id:'14.x2', tipo:'opcion', nivel:1, enunciado:'f(x) = x², de Z en Z, es:',
    opciones:['Inyectiva','Sobreyectiva','Ni inyectiva ni sobreyectiva'],
    correcta:2, explicacion:'No inyectiva: f(-2)=f(2)=4 es una colisión. No sobreyectiva: el 3 no es cuadrado de ningún entero.' },
  { id:'14.x2nat', tipo:'opcion', nivel:2, enunciado:'f(x) = x², de N en los cuadrados perfectos, es:',
    opciones:['Biyectiva','Solo inyectiva','Solo sobreyectiva'],
    correcta:0, explicacion:'En N no hay negativos que colisionen (inyectiva), y el codominio se restringió a exactamente los cuadrados que se producen (sobreyectiva). Biyectiva.' },
  { id:'14.palomar1', tipo:'vf', nivel:2, enunciado:'Si f: A → B es inyectiva y ambos son finitos, entonces |A| ≤ |B|.',
    respuesta:true, explicacion:'Cada elemento de A necesita una salida distinta en B; si A tuviera más elementos que B, dos tendrían que compartir salida.' },
  { id:'14.palomar2', tipo:'vf', nivel:2, enunciado:'El principio del palomar dice que si |A| > |B|, ninguna función de A en B puede ser inyectiva.',
    respuesta:true, explicacion:'Es una imposibilidad aritmética: con más entradas que salidas posibles, alguna salida se repite forzosamente.' },
  { id:'14.palomar3', tipo:'vf', nivel:2, enunciado:'En un grupo de 30 personas, el principio del palomar garantiza que al menos dos comparten el mes de nacimiento (12 meses posibles).',
    respuesta:true, explicacion:'30 personas repartidas entre 12 meses: como 30 > 12, al menos un mes debe repetirse en dos o más personas.' },
  { id:'14.refutar_iny', tipo:'opcion', nivel:1, enunciado:'Para refutar que una función es inyectiva, hay que:',
    opciones:['Exhibir dos entradas distintas con la misma salida (una colisión)','Probar que el dominio es finito','Mostrar que la imagen es todo el codominio'],
    correcta:0, explicacion:'Una colisión concreta —dos entradas distintas, misma salida— refuta la inyectividad de inmediato.' },
  { id:'14.refutar_sobre', tipo:'opcion', nivel:1, enunciado:'Para refutar que una función es sobreyectiva, hay que:',
    opciones:['Exhibir un elemento del codominio que ninguna entrada alcanza','Mostrar que hay una colisión','Mostrar que el dominio es infinito'],
    correcta:0, explicacion:'Basta un solo elemento del codominio sin preimagen para refutar la sobreyectividad.' },
],

15: [
  { id:'15.gf1', tipo:'formula', nivel:1, enunciado:'Con f(1)=a, f(2)=b, f(3)=a y g(a)=y, g(b)=x: calcula (g∘f)(1).',
    respuestas:['y'], explicacion:'(g∘f)(1) = g(f(1)) = g(a) = y.' },
  { id:'15.gf2', tipo:'formula', nivel:1, enunciado:'Con los mismos datos: calcula (g∘f)(2).',
    respuestas:['x'], explicacion:'(g∘f)(2) = g(f(2)) = g(b) = x.' },
  { id:'15.gf3', tipo:'formula', nivel:1, enunciado:'Con los mismos datos: calcula (g∘f)(3).',
    respuestas:['y'], explicacion:'(g∘f)(3) = g(f(3)) = g(a) = y (f(3) es a, igual que f(1)).' },
  { id:'15.orden', tipo:'vf', nivel:1, enunciado:'g∘f se lee «g después de f»: la que se aplica primero es f, la de la derecha.',
    respuesta:true, explicacion:'(g∘f)(x) = g(f(x)): primero entra x a f, y el resultado entra a g. Es contraintuitivo y fuente frecuente de errores.' },
  { id:'15.conmutativa', tipo:'vf', nivel:1, enunciado:'La composición de funciones es conmutativa en general: g∘f = f∘g.',
    respuesta:false, explicacion:'En general son distintas. Con f(x)=x+1, g(x)=x²: (g∘f)(x)=(x+1)² mientras (f∘g)(x)=x²+1.' },
  { id:'15.asociativa', tipo:'vf', nivel:1, enunciado:'La composición de funciones es asociativa: h∘(g∘f) = (h∘g)∘f.',
    respuesta:true, explicacion:'Sí lo es. Por eso tiene sentido hablar de una cadena de etapas sin preocuparse por los paréntesis.' },
  { id:'15.formula1', tipo:'formula', nivel:2, enunciado:'Con f(x) = x + 2 y g(x) = 3x: calcula (g ∘ f)(x). (escribe la expresión simplificada, ej: 3x+6)',
    respuestas:['3x+6','3(x+2)'], explicacion:'(g∘f)(x) = g(f(x)) = g(x+2) = 3(x+2) = 3x+6.' },
  { id:'15.formula2', tipo:'formula', nivel:2, enunciado:'Con las mismas f y g: calcula (f ∘ g)(x).',
    respuestas:['3x+2'], explicacion:'(f∘g)(x) = f(g(x)) = f(3x) = 3x+2. Nótese que es distinto de (g∘f)(x) = 3x+6: la composición no es conmutativa.' },
  { id:'15.hereda', tipo:'vf', nivel:2, enunciado:'Si f y g son ambas inyectivas, entonces g∘f también es inyectiva.',
    respuesta:true, explicacion:'La inyectividad se hereda en la composición: si ninguna de las dos etapas colapsa entradas distintas, la cadena completa tampoco.' },
  { id:'15.compat', tipo:'opcion', nivel:2, enunciado:'Para que g∘f exista, se necesita que:',
    opciones:['La imagen de f esté contenida en el dominio de g','f y g tengan el mismo dominio','g sea inyectiva'],
    correcta:0, explicacion:'Cada salida de f tiene que ser una entrada legítima para g. Si un solo valor de salida de f no cabe en g, la composición falla ahí: es el expediente que se atora.' },
],

16: [
  { id:'16.criterio', tipo:'opcion', nivel:1, enunciado:'f: A → B tiene función inversa si y solo si f es:',
    opciones:['Biyectiva','Solo inyectiva','Solo sobreyectiva'],
    correcta:0, explicacion:'Necesita las dos condiciones a la vez: inyectiva para que la unicidad se conserve al invertir, y sobreyectiva para que la totalidad se conserve.' },
  { id:'16.calc', tipo:'formula', nivel:2, enunciado:'Calcula la inversa de f(x) = 2x + 3. Escríbela en términos de y (o x), ej: (y-3)/2',
    respuestas:['(y-3)/2','(x-3)/2'], explicacion:'Se despeja de y=2x+3: x=(y-3)/2, luego f⁻¹(y) = (y-3)/2.' },
  { id:'16.x2inv', tipo:'vf', nivel:1, enunciado:'f(x) = x² sobre todos los reales tiene función inversa.',
    respuesta:false, explicacion:'No es inyectiva (f(-3)=f(3)=9) ni sobreyectiva (el -1 no es imagen de nadie). No se puede invertir tal como está.' },
  { id:'16.restringir', tipo:'opcion', nivel:2, enunciado:'Para que f(x) = x² tenga inversa, hay que:',
    opciones:['Restringir el dominio y el codominio a [0, ∞)','No es posible bajo ninguna restricción','Solo restringir el codominio'],
    correcta:0, explicacion:'Sobre [0,∞) con codominio [0,∞), f es biyectiva y su inversa es f⁻¹(y)=√y. La fórmula no cambia; cambia el dominio y codominio declarados.' },
  { id:'16.falla1', tipo:'vf', nivel:2, enunciado:'Si f no es inyectiva, al invertir la relación falla la unicidad.',
    respuesta:true, explicacion:'Un elemento de B con dos preimágenes distintas, al dar vuelta, tendría dos imágenes: eso rompe la unicidad de la relación invertida.' },
  { id:'16.falla2', tipo:'vf', nivel:2, enunciado:'Si f no es sobreyectiva, al invertir la relación falla la totalidad.',
    respuesta:true, explicacion:'Un elemento de B sin preimagen, al dar vuelta, se queda sin imagen: eso rompe la totalidad de la relación invertida.' },
  { id:'16.escalera1', tipo:'opcion', nivel:1, enunciado:'«Una relación con totalidad y unicidad» es, por definición, una:',
    opciones:['Función','Partición','Biyección'],
    correcta:0, explicacion:'Es exactamente la definición de función del módulo 4.' },
  { id:'16.escalera2', tipo:'opcion', nivel:1, enunciado:'«Una función inyectiva y sobreyectiva a la vez» es, por definición, una:',
    opciones:['Relación de equivalencia','Biyección','Orden parcial'],
    correcta:1, explicacion:'Es la definición de biyección, y es exactamente lo único que se puede deshacer (tiene inversa).' },
],

};
